export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const GET_NAME_COUNTRIES = "GET_NAME_COUNTRIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_NAME_COUNTRIES_FORM = "GET_NAME_COUNTRIES_FORM";
export const FILTER_ACTIVITY = "FILTER_ACTIVITY";
export const FILTER_BY_ALPHA= "FILTER_BY_ALPHA";
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const POPULATION_ORDER = "POPULATION_ORDER";
export const FILTER_CLIENT = "FILTER_CLIENT";




